parameters:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET build - ${{ parameters.buildConfiguration }}'
  inputs:
    command: build
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: '.NET publish - ${{ parameters.buildConfiguration }}'
  inputs:
    command: publish
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'
    zipAfterPublish: true